# Generated by Django 6.0.7 on 2026-08-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_activity_action_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pending_approval',
            field=models.BooleanField(default=False, help_text='Menunggu persetujuan admin (dari registrasi mandiri).'),
        ),
    ]
