# Generated by Django 6.0.7 on 2026-08-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_notification_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Sokkafiber Helpdesk', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Internal IT Support', max_length=200)),
                ('footer_text', models.CharField(blank=True, default='Sokkafiber Helpdesk · Internal IT Support', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Kosongkan untuk memakai logo bawaan.', null=True, upload_to='brand/')),
                ('primary_color', models.CharField(default='#4f46e5', help_text='Warna aksen, format hex (mis. #4f46e5).', max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Ditulis dengan Markdown.'),
        ),
    ]
