# Generated by Django 6.0.7 on 2026-08-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_appsettings_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_overdue_sent',
            field=models.BooleanField(default=False, help_text='Notifikasi terlampaui SLA sudah dikirim.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_warning_sent',
            field=models.BooleanField(default=False, help_text='Notifikasi mendekati SLA sudah dikirim.'),
        ),
    ]
