# Generated by Django 6.0.7 on 2026-08-18 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_profile_avatar_profile_job_title_profile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nama singkat untuk judul template.', max_length=100)),
                ('content', models.TextField(help_text='Isi jawaban template. Gunakan {ticket_id} dan {requester} sebagai placeholder.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Kategori tiket yang cocok.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.category')),
                ('company', models.ForeignKey(blank=True, help_text='Kosongkan untuk template global.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canned_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
